-- Brouillons du Suivi Client : migration idempotente compatible MySQL 5.7+.
-- La table client_reglements existante est réutilisée ; aucune table parallèle.

SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'client_reglements' AND column_name = 'numero_brouillon') = 0, 'ALTER TABLE client_reglements ADD COLUMN numero_brouillon VARCHAR(32) NULL AFTER id', 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'client_reglements' AND column_name = 'statut') = 0, "ALTER TABLE client_reglements ADD COLUMN statut ENUM('BROUILLON','VALIDE','SUPPRIME') NOT NULL DEFAULT 'VALIDE' AFTER date_mouvement", 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'client_reglements' AND column_name = 'updated_at') = 0, 'ALTER TABLE client_reglements ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at', 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'client_reglements' AND column_name = 'validated_at') = 0, 'ALTER TABLE client_reglements ADD COLUMN validated_at DATETIME NULL AFTER updated_at', 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'client_reglements' AND column_name = 'deleted_at') = 0, 'ALTER TABLE client_reglements ADD COLUMN deleted_at DATETIME NULL AFTER validated_at', 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'client_reglements' AND index_name = 'uq_client_reglements_numero_brouillon') = 0, 'CREATE UNIQUE INDEX uq_client_reglements_numero_brouillon ON client_reglements (numero_brouillon)', 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'client_reglements' AND index_name = 'idx_client_reglements_brouillons') = 0, 'CREATE INDEX idx_client_reglements_brouillons ON client_reglements (statut, deleted_at, updated_at)', 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;

-- CaisseService est appelé uniquement après validation. Ces champs et statuts
-- lui permettent d’enregistrer l’encaissement et son écriture comptable.
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'mouvements_caisse' AND column_name = 'solde_avant') = 0, 'ALTER TABLE mouvements_caisse ADD COLUMN solde_avant DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER montant', 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'mouvements_caisse' AND column_name = 'solde_apres') = 0, 'ALTER TABLE mouvements_caisse ADD COLUMN solde_apres DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER solde_avant', 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'mouvements_caisse' AND column_name = 'supprime') = 0, 'ALTER TABLE mouvements_caisse ADD COLUMN supprime TINYINT(1) NOT NULL DEFAULT 0 AFTER ecriture_id', 'SELECT 1'); PREPARE migration_stmt FROM @sql; EXECUTE migration_stmt; DEALLOCATE PREPARE migration_stmt;
ALTER TABLE mouvements_caisse MODIFY COLUMN type_mouvement ENUM('VENTE','REMBOURSEMENT','APPROVISIONNEMENT','RETRAIT','AJUSTEMENT','ENCAISSEMENT_CLIENT','REGLEMENT_CREANCE','ACOMPTE_CLIENT','DEPOT_BANCAIRE','DECAISSEMENT','ANNULATION_VENTE','RETRAIT_BANCAIRE') NOT NULL;
