<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= htmlspecialchars($title ?? 'Ordonnances') ?></title><link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"></head>
<body class="bg-gray-100 min-h-screen"><main class="max-w-7xl mx-auto p-5 md:p-8">
<div class="flex flex-wrap items-center justify-between gap-3 mb-6"><div><h1 class="text-2xl font-bold text-gray-900"><i class="fas fa-file-medical text-blue-600 mr-2"></i>Ordonnances</h1><p class="text-sm text-gray-500">Consultation et préparation de vente sans mouvement de stock.</p></div><a href="<?= htmlspecialchars($returnTo ?? '/vente') ?>" class="px-4 py-2 rounded bg-gray-600 text-white"><i class="fas fa-arrow-left mr-1"></i>Dashboard vente</a></div>
<form method="get" action="/ordonnances" class="bg-white rounded-lg shadow p-4 grid grid-cols-1 md:grid-cols-5 gap-3 mb-5">
<input name="numero" value="<?= htmlspecialchars($filtres['numero'] ?? '') ?>" placeholder="N° ordonnance" class="border rounded px-3 py-2"><input name="patient" value="<?= htmlspecialchars($filtres['patient'] ?? '') ?>" placeholder="Patient / client" class="border rounded px-3 py-2"><input name="prescripteur" value="<?= htmlspecialchars($filtres['prescripteur'] ?? '') ?>" placeholder="Prescripteur" class="border rounded px-3 py-2"><input type="date" name="date" value="<?= htmlspecialchars($filtres['date'] ?? '') ?>" class="border rounded px-3 py-2"><button class="bg-blue-600 hover:bg-blue-700 text-white rounded px-4 py-2"><i class="fas fa-search mr-1"></i>Rechercher</button></form>
<div class="bg-white shadow rounded-lg overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-gray-600"><tr><th class="text-left p-3">Numéro</th><th class="text-left p-3">Date</th><th class="text-left p-3">Patient</th><th class="text-left p-3">Prescripteur</th><th class="text-center p-3">Statut</th><th class="text-center p-3">Produits</th><th class="text-right p-3">Actions</th></tr></thead><tbody>
<?php foreach (($ordonnances ?? []) as $ordonnance): ?><tr class="border-t"><td class="p-3 font-medium"><?= htmlspecialchars($ordonnance['numero_ordonnance']) ?></td><td class="p-3"><?= htmlspecialchars($ordonnance['date_ordonnance']) ?></td><td class="p-3"><?= htmlspecialchars($ordonnance['nom_patient'] ?: 'Non renseigné') ?></td><td class="p-3"><?= htmlspecialchars($ordonnance['nom_medecin'] ?: 'Non renseigné') ?></td><td class="p-3 text-center"><span class="px-2 py-1 rounded-full text-xs <?= $ordonnance['statut'] === 'DISPENSEE' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700' ?>"><?= htmlspecialchars($ordonnance['statut']) ?></span></td><td class="p-3 text-center"><?= (int)$ordonnance['nombre_produits'] ?></td><td class="p-3 text-right space-x-2"><a class="text-blue-600" href="/ordonnances/voir/<?= (int)$ordonnance['id'] ?>"><i class="fas fa-eye"></i> Voir</a><a class="text-green-600" href="/ordonnances/traiter/<?= (int)$ordonnance['id'] ?>"><i class="fas fa-cash-register"></i> Traiter</a></td></tr><?php endforeach; ?>
<?php if (empty($ordonnances)): ?><tr><td colspan="7" class="p-8 text-center text-gray-500">Aucune ordonnance ne correspond à la recherche.</td></tr><?php endif; ?></tbody></table></div>
</main></body></html>
